"""
Run every tagged query in queries.sql against rent.db and print a labelled result.
Run from the sql/ folder:   python run_queries.py
(Also writes query_results.md so the answers travel with the repo.)
"""
import sqlite3, re
import pandas as pd
from pathlib import Path

HERE = Path(__file__).resolve().parent
DB = HERE / "rent.db"
if not DB.exists():
    raise SystemExit("rent.db not found — run build_db.py first.")

sql_text = (HERE / "queries.sql").read_text()
# split into (name, question, body) using the -- @name | question tags
blocks = re.split(r"--\s*@(\w+)\s*\|\s*(.*)", sql_text)
con = sqlite3.connect(DB)

md = ["# Query results — Mumbai Rent Radar\n",
      "_Generated by `run_queries.py`. Each block is a self-contained analytical query._\n"]
i = 1
while i < len(blocks) - 2:
    name, question, body = blocks[i], blocks[i + 1].strip(), blocks[i + 2]
    body = body.split(";")[0].strip() + ";"
    try:
        res = pd.read_sql_query(body, con)
        print(f"\n=== {name} — {question} ===")
        print(res.to_string(index=False))
        md += [f"\n## {name}\n**{question}**\n", "```", res.to_string(index=False), "```\n"]
    except Exception as e:
        print(f"\n=== {name} FAILED: {e}")
    i += 3

con.close()
(HERE / "query_results.md").write_text("\n".join(md), encoding="utf-8")
print("\nWrote query_results.md")
